In [28]:
from nytimesarticle import articleAPI
import os
import urllib3
import urllib.request as ur
import pandas as pd
import simplejson as json
import time
from itertools import chain

In [10]:
nyt_api = articleAPI(nyt_key)

In [52]:
nyt_key = 'df862df13bf04ee09248474f1707bafa'

nyt_api = 'https://api.nytimes.com/svc/search/v2/articlesearch.'
out_format = 'json'

begin_date = '20180624'
end_date = '20180625'
date = 'begin_date=' + begin_date + '&' + 'end_date=' + end_date + '&'

offset = 0
pages  =  100
url = nyt_api + out_format + '?' + date + 'offset=' + str(offset) + '&' + 'api-key=' + nyt_key
print(url)

https://api.nytimes.com/svc/search/v2/articlesearch.json?begin_date=20180624&end_date=20180625&offset=0&api-key=df862df13bf04ee09248474f1707bafa

In [54]:
dicts = []
for i in range(0, pages):
    offset = i
    url = nyt_api + out_format + '?' + date + 'offset=' + str(offset) + '&' + 'api-key=' + nyt_key
    response = ur.urlopen(url).read()
    dict_response = json.loads(response, encoding = 'utf-8')
    response = dict_response['response']
    docs = response['docs']
    dicts.append(docs)
    time.sleep(0.5)

In [77]:
df = pd.DataFrame(list(chain.from_iterable(dicts)))
df[['pub_date']] = df['pub_date'].str.replace('T00:00:00Z','')

In [79]:
dicts[0][0].keys()

dict_keys(['web_url', 'snippet', 'blog', 'source', 'multimedia', 'headline', 'keywords', 'pub_date', 'document_type', 'news_desk', 'section_name', 'byline', 'type_of_material', '_id', 'word_count', 'score', 'uri'])

In [85]:
df.head()

,_id,blog,byline,document_type,headline,keywords,multimedia,news_desk,print_page,pub_date,score,section_name,slideshow_credits,snippet,source,type_of_material,uri,web_url,word_count
0,5b2edf8247de81a90122f4ba,{},"{'original': 'By THE ASSOCIATED PRESS', 'perso...",article,"{'main': 'Tavares' Future, Flames-Hurricanes T...",[],[],None,NaN,2018-06-24T00:02:02+0000,1.0,Hockey,NaN,Ilya Kovalchuk signed with the Kings in his re...,AP,News,nyt://article/a487e041-ba9e-5fb8-a257-dc328c4b...,https://www.nytimes.com/aponline/2018/06/23/sp...,762
1,5b2eecd747de81a90122f4c1,{},"{'original': 'By REUTERS', 'person': [], 'orga...",article,{'main': 'Mexico Pride March Poses Questions f...,[],[],None,NaN,2018-06-24T00:59:02+0000,1.0,Americas,NaN,Tens of thousands of gay rights supporters mar...,Reuters,News,nyt://article/5ce14a1e-f48a-5a60-890d-cf445f31...,https://www.nytimes.com/reuters/2018/06/23/wor...,509
2,5b307c9e00a1bc2872e64f7c,{},"{'original': 'By REUTERS', 'person': [], 'orga...",article,{'main': 'Lopetegui Shadow Hangs Over Spain Ah...,[],[],None,NaN,2018-06-24T10:10:59+0000,1.0,Soccer,NaN,The shadow of the dramatic sacking of coach Ju...,Reuters,News,nyt://article/aeaa6052-b0d6-522d-88ca-08feb0dc...,https://www.nytimes.com/reuters/2018/06/24/spo...,339
3,5b2f174347de81a90122f4dc,{},"{'original': None, 'person': None, 'organizati...",article,"{'main': 'Emi Nietfeld, Byron Hood', 'kicker':...","[{'name': 'subject', 'value': 'Weddings and En...","[{'rank': 0, 'subtype': 'xlarge', 'caption': N...",Society,14,2018-06-24T04:00:00+0000,1.0,Weddings,NaN,"The couple met in San Francisco, in 2014, thro...",The New York Times,News,nyt://article/870c9cb2-680a-5278-afe9-dadab9c5...,https://www.nytimes.com/2018/06/24/fashion/wed...,219
4,5b2f174847de81a90122f4e5,{},"{'original': None, 'person': None, 'organizati...",article,"{'main': 'Ashley Fischer, Jonathan Mabry', 'ki...","[{'name': 'subject', 'value': 'Weddings and En...","[{'rank': 0, 'subtype': 'xlarge', 'caption': N...",Society,12,2018-06-24T04:00:00+0000,1.0,Weddings,NaN,The couple met in 2014 through the dating app ...,The New York Times,News,nyt://article/07079064-d017-59da-a5ae-30e739c4...,https://www.nytimes.com/2018/06/24/fashion/wed...,180